/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegistrasiLobRouteImport } from './routes/registrasi-lob'
import { Route as ProdukLokalRouteImport } from './routes/produk-lokal'
import { Route as PenginapanRouteImport } from './routes/penginapan'
import { Route as HattaMarineProgramRouteImport } from './routes/hatta-marine-program'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrasiLobRoute = RegistrasiLobRouteImport.update({
  id: '/registrasi-lob',
  path: '/registrasi-lob',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukLokalRoute = ProdukLokalRouteImport.update({
  id: '/produk-lokal',
  path: '/produk-lokal',
  getParentRoute: () => rootRouteImport,
} as any)
const PenginapanRoute = PenginapanRouteImport.update({
  id: '/penginapan',
  path: '/penginapan',
  getParentRoute: () => rootRouteImport,
} as any)
const HattaMarineProgramRoute = HattaMarineProgramRouteImport.update({
  id: '/hatta-marine-program',
  path: '/hatta-marine-program',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hatta-marine-program': typeof HattaMarineProgramRoute
  '/penginapan': typeof PenginapanRoute
  '/produk-lokal': typeof ProdukLokalRoute
  '/registrasi-lob': typeof RegistrasiLobRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hatta-marine-program': typeof HattaMarineProgramRoute
  '/penginapan': typeof PenginapanRoute
  '/produk-lokal': typeof ProdukLokalRoute
  '/registrasi-lob': typeof RegistrasiLobRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hatta-marine-program': typeof HattaMarineProgramRoute
  '/penginapan': typeof PenginapanRoute
  '/produk-lokal': typeof ProdukLokalRoute
  '/registrasi-lob': typeof RegistrasiLobRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hatta-marine-program'
    | '/penginapan'
    | '/produk-lokal'
    | '/registrasi-lob'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hatta-marine-program'
    | '/penginapan'
    | '/produk-lokal'
    | '/registrasi-lob'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/hatta-marine-program'
    | '/penginapan'
    | '/produk-lokal'
    | '/registrasi-lob'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HattaMarineProgramRoute: typeof HattaMarineProgramRoute
  PenginapanRoute: typeof PenginapanRoute
  ProdukLokalRoute: typeof ProdukLokalRoute
  RegistrasiLobRoute: typeof RegistrasiLobRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrasi-lob': {
      id: '/registrasi-lob'
      path: '/registrasi-lob'
      fullPath: '/registrasi-lob'
      preLoaderRoute: typeof RegistrasiLobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk-lokal': {
      id: '/produk-lokal'
      path: '/produk-lokal'
      fullPath: '/produk-lokal'
      preLoaderRoute: typeof ProdukLokalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penginapan': {
      id: '/penginapan'
      path: '/penginapan'
      fullPath: '/penginapan'
      preLoaderRoute: typeof PenginapanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hatta-marine-program': {
      id: '/hatta-marine-program'
      path: '/hatta-marine-program'
      fullPath: '/hatta-marine-program'
      preLoaderRoute: typeof HattaMarineProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HattaMarineProgramRoute: HattaMarineProgramRoute,
  PenginapanRoute: PenginapanRoute,
  ProdukLokalRoute: ProdukLokalRoute,
  RegistrasiLobRoute: RegistrasiLobRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
